---
# https://backstage.io/docs/features/software-catalog/descriptor-format#kind-system
apiVersion: backstage.io/v1alpha1
kind: System
metadata:
  name: examples
spec:
  owner: guests
---
# https://backstage.io/docs/features/software-catalog/descriptor-format#kind-component
apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: example-website
  annotations:
    backstage.io/kubernetes-id: example-website
    backstage.io/kubernetes-namespace: default
spec:
  type: website
  lifecycle: experimental
  owner: guests
  system: examples
  providesApis: [example-grpc-api]
---
# https://backstage.io/docs/features/software-catalog/descriptor-format#kind-api
apiVersion: backstage.io/v1alpha1
kind: API
metadata:
  name: example-grpc-api
spec:
  type: grpc
  lifecycle: experimental
  owner: guests
  system: examples
  definition: |
    syntax = "proto3";

    service Exampler {
      rpc Example (ExampleMessage) returns (ExampleMessage) {};
    }

    message ExampleMessage {
      string example = 1;
    };
---
apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: toystore
  annotations:
    backstage.io/kubernetes-id: toystore
    backstage.io/kubernetes-namespace: toystore
spec:
  type: service
  lifecycle: experimental
  owner: guests
  system: examples
  providesApis: [toystore-api]
---
# toystore-api is now auto-synced from the kubernetes apiproduct cr
# by the apiproduct entity provider - no need to define it manually
# users and groups are defined in users.yaml
