---
apiVersion: backstage.io/v1alpha1
kind: User
metadata:
  name: platform-engineer
spec:
  profile:
    displayName: Platform Engineer
    email: platform-engineer@example.com
  memberOf: [platform-engineers]
---
apiVersion: backstage.io/v1alpha1
kind: User
metadata:
  name: api-owner
spec:
  profile:
    displayName: API Owner
    email: api-owner@example.com
  memberOf: [api-owners]
---
apiVersion: backstage.io/v1alpha1
kind: User
metadata:
  name: api-consumer
spec:
  profile:
    displayName: API Consumer
    email: api-consumer@example.com
  memberOf: [api-consumers]
---
apiVersion: backstage.io/v1alpha1
kind: Group
metadata:
  name: platform-engineers
  description: platform administrators who manage infrastructure and policies
spec:
  type: team
  children: []
---
apiVersion: backstage.io/v1alpha1
kind: Group
metadata:
  name: api-owners
  description: api owners who publish apis and approve access requests
spec:
  type: team
  children: []
---
apiVersion: backstage.io/v1alpha1
kind: Group
metadata:
  name: api-consumers
  description: developers who consume apis
spec:
  type: team
  children: []
