apiVersion: v1
kind: Namespace
metadata:
  name: rhdh
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: rhdh-kuadrant
  namespace: rhdh
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: rhdh-kuadrant-reader
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: rhdh-kuadrant-reader
subjects:
  - kind: ServiceAccount
    name: rhdh-kuadrant
    namespace: rhdh
