apiVersion: v1
kind: ConfigMap
metadata:
  name: gateway-parameters
  namespace: api-gateway
data:
  service: |
    spec:
      loadBalancerClass: oinc.io/metallb
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: gateway-parameters
  namespace: gamestore
data:
  service: |
    spec:
      loadBalancerClass: oinc.io/metallb
